Create a class encrypt, create menu
MrSantiaga/AccountManager pull request #1
Opened 2024-03-11 21:08 UTC by AlexaZhuk

2024-03-11 21:29 UTC, MrSantiaga requested changes

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Dates.cs
> +	internal class Dates
Dates -> UserCredentials

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Encryptor.cs
> +		private byte[] GetLogin(string login)
Add blank line

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Encryptor.cs
> +		private byte[] GetVector(string vector)
Add blank line

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Encryptor.cs
> +
extra line

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Encryptor.cs
> +
{}

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +			Console.WriteLine("Menu: \n1. - Add new credentails \n2. - List all credentiles \n3. - Find and show credentiles \n4. - Delete credentiles \n0. - Exit");
Better use multiple `Console.WriteLine` to increase readability

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +			bool tryParse = int.TryParse(Console.ReadLine(), out int choose);
tryParse -> isParsed

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						Encryptor first = new Encryptor();
first -> encryptor

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						Console.WriteLine("Do you want to return to menu?\n 1. - Yes\n 2. - No");
Multiple `Console.WriteLine`

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						int answerRetutn = int.Parse(Console.ReadLine());
typo

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							Menu();
Recusive call. Replace with loop

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						string passwordRepeat = Console.ReadLine();
passwordRepeat -> passwordConfirmation

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Dates.cs
> +		public List<Alllogins> allLogins { get; set; }
NIT: Looks like wrong prototyping

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Alllogins.cs
> +		List<string> userLogins { get; set; }
From upper case

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Dates.cs
> +		public List<Alllogins> allLogins { get; set; }
From upper case

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Encryptor.cs
> +		public Encryptor() : this("ho-ho-ho")
NIT: Let's have more secure vector

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						Encryptor first = new Encryptor();
Encryptor is IDisposable

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						int answerRetutn = int.Parse(Console.ReadLine());
Always use TryParse

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						Console.WriteLine("Repeat your password, please");
Repeat your password -> Confirm your password

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						Dates user = new Dates();
user -> credentials

2024-03-11 21:29 UTC, MrSantiaga commented on AccountManager/Program.cs
> +			while ((!tryParse) || (choose < 0 || choose > 5))
Try to rework to use switch statement inside this loop

2024-03-12 16:23 UTC, AlexaZhuk commented on AccountManager/Dates.cs
> +	internal class Dates
OK

2024-03-14 13:47 UTC, MrSantiaga requested changes

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Encryptor.cs
> +		public string Encrypt(string password, string key)
password -> plainText

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +		static public void Menu()
public static

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							string keyCofirm = Console.ReadLine();
typo

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							bool tryParse2 = int.TryParse(Console.ReadLine(), out int answerRetutn);
typo: answerRetutn

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							bool tryParse2 = int.TryParse(Console.ReadLine(), out int answerRetutn);
code duplication
move to while

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +								continue;
Looks like invalid if statement

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							string userLogin = Console.ReadLine();
NIT: userLogin -> login

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +			Console.WriteLine("1. - Add new credentails ");
typo: credentials

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +			Console.WriteLine("Do you want to return to menu?\n 1. - Yes\n 2. - No");
Multiple `Console.WriteLine`

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +		public static void AddUserDatesJson(string login, string encryptedPassword)
AddUser

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +		public static void GetSearch(string userLogin)
SearchByLogin

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						using Encryptor first = new Encryptor();
first-> encryptor

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							string toDecrypt = first.Decrypt(user.Password, key);
decryptedPassword

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +		public static void GetDelete()
Rework to have `DeleteByLogin(string login)`

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +						using Encryptor first = new Encryptor();
encryptor

Encryptor may be global

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							string resultTry = JsonConvert.SerializeObject(dataBase);
resultJson or serializedText

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +							Console.WriteLine("Your code is wrong. Try again");
Your key

2024-03-14 13:47 UTC, MrSantiaga commented on AccountManager/Program.cs
> +		public static void AddUser(string login, string password, string key)
why do we have `AddUserDatesJson` and `AddUser` with almost same logic?

2024-03-14 15:38 UTC, MrSantiaga requested changes

2024-03-14 15:38 UTC, MrSantiaga commented on AccountManager/Encryptor.cs
> +
**EXTRA LINES**

2024-03-14 15:38 UTC, MrSantiaga commented on AccountManager/Program.cs
> +		}
`encryptor.Dispose()`

2024-03-14 15:38 UTC, MrSantiaga commented on AccountManager/Program.cs
> +					//Console.WriteLine($"your login is {user.Login} password is {user.Password}");
Remove

2024-03-14 15:38 UTC, MrSantiaga commented on AccountManager/Program.cs
> +			UserData user1 = new UserData();
user

2024-03-14 15:44 UTC, MrSantiaga approved these changes

2024-03-14 15:45 UTC, merged